#ifndef _STIROPCODES_H_
#define _STIROPCODES_H_

enum stir_opcode {
  STIR_OPCODE_TOP_DIR = 64,
  STIR_OPCODE_CUR_DIR_FROM_TOP = 65,
  STIR_OPCODE_DEP_ADD = 66,
  STIR_OPCODE_RULE_ADD = 67,
  STIR_OPCODE_SUFSUBALL = 68,
  STIR_OPCODE_SUFSUBONE = 69,
  STIR_OPCODE_SUFFILTER = 70,
  STIR_OPCODE_PATHSUFFIX = 71,
  STIR_OPCODE_PATHBASENAME = 72,
  STIR_OPCODE_PATHDIR = 73,
  STIR_OPCODE_PATHNOTDIR = 74,
  STIR_OPCODE_PATHSIMPLIFY = 75,
  STIR_OPCODE_PATHSUFFIXALL = 76,
  STIR_OPCODE_PATHBASENAMEALL = 77,
  STIR_OPCODE_PATHDIRALL = 78,
  STIR_OPCODE_PATHNOTDIRALL = 79,
  STIR_OPCODE_PATHSIMPLIFYALL = 80,
  STIR_OPCODE_GLOB = 81,
  STIR_OPCODE_JSON_IN = 82,
  STIR_OPCODE_SUFFILTEROUT = 83,
};

#endif
